# Generated by Django 4.2 on 2023-08-24 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0013_ptkptype'),
        ('employees', '0026_alter_employees_expired_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='ptkp_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ptkp_type_id', to='benefits.ptkptype'),
        ),
    ]
