# Generated by Django 4.2 on 2023-09-09 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0027_employees_ptkp_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='expired_at',
            field=models.DateField(default=datetime.date(2024, 9, 8)),
        ),
    ]
