# Generated by Django 4.2 on 2023-12-25 04:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0028_alter_employees_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='birthplace',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='expired_at',
            field=models.DateField(blank=True, default=datetime.date(2024, 12, 24), null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='province',
            field=models.CharField(blank=True, choices=[('Nanggroe Aceh Darussalam', 'Nanggroe Aceh Darussalam'), ('Sumatera Utara', 'Sumatera Utara'), ('Sumatera Selatan', 'Sumatera Selatan'), ('Sumatera Barat', 'Sumatera Barat'), ('Bengkulu', 'Bengkulu'), ('Riau', 'Riau'), ('Kepulauan Riau', 'Kepulauan Riau'), ('Jambi', 'Jambi'), ('Lampung', 'Lampung'), ('Bangka Belitung', 'Bangka Belitung'), ('Kalimantan Barat', 'Kalimantan Barat'), ('Kalimantan Timur', 'Kalimantan Timur'), ('Kalimantan Selatan', 'Kalimantan Selatan'), ('Kalimantan Tengah', 'Kalimantan Tengah'), ('Kalimantan Utara', 'Kalimantan Utara'), ('Banten', 'Banten'), ('DKI Jakarta', 'DKI Jakarta'), ('Jawa Barat', 'Jawa Barat'), ('Jawa Tengah', 'Jawa Tengah'), ('Daerah Istimewa Yogyakarta', 'Daerah Istimewa Yogyakarta'), ('Jawa Timur', 'Jawa Timur'), ('Bali', 'Bali'), ('Nusa Tenggara Timur', 'Nusa Tenggara Timur'), ('Nusa Tenggara Barat', 'Nusa Tenggara Barat'), ('Gorontalo', 'Gorontalo'), ('Sulawesi Barat', 'Sulawesi Barat'), ('Sulawesi Tengah', 'Sulawesi Tengah'), ('Sulawesi Utara', 'Sulawesi Utara'), ('Sulawesi Tenggara', 'Sulawesi Tenggara'), ('Sulawesi Selatan', 'Sulawesi Selatan'), ('Maluku Utara', 'Maluku Utara'), ('Maluku', 'Maluku'), ('Papua Barat', 'Papua Barat'), ('Papua', 'Papua'), ('Papua Tengah', 'Papua Tengah'), ('Papua Pegunungan', 'Papua Pegunungan'), ('Papua Selatan', 'Papua Selatan'), ('Papua Barat Daya', 'Papua Barat Daya')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='rt',
            field=models.CharField(blank=True, default='00', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='rw',
            field=models.CharField(blank=True, default='00', max_length=4, null=True),
        ),
    ]
