# Generated by Django 4.2 on 2023-12-25 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0015_alter_ptkptype_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0031_alter_employees_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='birthplace',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='bloodtype',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='domicile',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='education',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='expired_at',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='province',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='resigned_at',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='rt',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='rw',
        ),
        migrations.AlterField(
            model_name='employees',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employees',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_by_employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employees',
            name='ptkp_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ptkp_type_id', to='benefits.ptkptype'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by_employees', to=settings.AUTH_USER_MODEL),
        ),
    ]
