# Generated by Django 4.2 on 2023-12-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0032_remove_employees_address_remove_employees_birthplace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='nik',
            field=models.CharField(blank=True, default='', max_length=20, null=True, unique=True),
        ),
    ]
