# Generated by Django 4.2 on 2023-07-18 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0018_alter_employees_expired_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.TextField(blank=True, default='', max_length=400, null=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='created_by_payroll_period', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_by_payroll_period', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_payroll_period', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Payroll Period',
                'db_table': 'payroll_period',
                'permissions': (('create_payroll_period', 'Create Payroll Period'), ('read_payroll_period', 'Read Payroll Period'), ('update_payroll_period', 'Update Payroll Period'), ('delete_payroll_period', 'Delete Payroll Period')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Salaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('presence_count', models.IntegerField(db_column='presence_count')),
                ('total_work_hours', models.IntegerField(db_column='total_work_hours')),
                ('ptkp', models.IntegerField(db_column='ptkp')),
                ('overtime_hours_count', models.IntegerField(db_column='overtime_hours_count')),
                ('overtime_hours_nominal', models.IntegerField(db_column='overtime_hours_nominal')),
                ('leave_count', models.IntegerField(db_column='leave_count')),
                ('sick_count', models.IntegerField(db_column='sick_count')),
                ('permit_count', models.IntegerField(db_column='permit_count')),
                ('pph21', models.IntegerField(db_column='pph21')),
                ('allowance', models.IntegerField(db_column='allowance')),
                ('deduction', models.IntegerField(db_column='deduction')),
                ('base_salary', models.IntegerField(db_column='base_salary')),
                ('bonus', models.IntegerField(db_column='bonus')),
                ('gross_salary', models.IntegerField(db_column='gross_salary')),
                ('final_salary', models.IntegerField(db_column='final_salary')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='created_by_salaries', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_by_salaries', to=settings.AUTH_USER_MODEL)),
                ('employee_id', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='employees.employees')),
                ('period_id', models.ForeignKey(db_column='period_id', on_delete=django.db.models.deletion.CASCADE, to='salaries.payrollperiods')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_salaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Salaries',
                'db_table': 'salaries',
                'permissions': (('create_salaries', 'Create Salaries'), ('read_salaries', 'Read Salaries'), ('update_salaries', 'Update Salaries'), ('delete_salaries', 'Delete Salaries')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SalaryComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='', max_length=400, null=True)),
                ('is_deduction', models.BooleanField(default=False)),
                ('is_adjustment', models.BooleanField(default=False)),
                ('updated_value', models.IntegerField(db_column='updated_value')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='created_by_salaries_components', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_by_salaries_components', to=settings.AUTH_USER_MODEL)),
                ('employee_id', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='employees.employees')),
                ('period_id', models.ForeignKey(db_column='period_id', on_delete=django.db.models.deletion.CASCADE, to='salaries.payrollperiods')),
                ('salary_id', models.ForeignKey(db_column='salary_id', on_delete=django.db.models.deletion.CASCADE, to='salaries.salaries')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_salaries_components', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Salary Components',
                'db_table': 'salary_components',
                'permissions': (('create_salary_components', 'Create Salary Components'), ('read_salary_components', 'Read Salary Components'), ('update_salary_components', 'Update Salary Components'), ('delete_salary_components', 'Delete Salary Components')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SalaryAdjustments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='', max_length=400, null=True)),
                ('is_deduction', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='created_by_salary_adjustments', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_by_salary_adjustments', to=settings.AUTH_USER_MODEL)),
                ('salary_id', models.ForeignKey(db_column='salary_id', on_delete=django.db.models.deletion.CASCADE, to='salaries.salaries')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_salary_adjustments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Salary Adjustments',
                'db_table': 'salary_adjustments',
                'permissions': (('create_salary_adjustments', 'Create Salary Adjustments'), ('read_salary_adjustments', 'Read Salary Adjustments'), ('update_salary_adjustments', 'Update Salary Adjustments'), ('delete_salary_adjustments', 'Delete Salary Adjustments')),
                'default_permissions': (),
            },
        ),
    ]
