# Generated by Django 4.2 on 2023-07-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salarycomponents',
            old_name='is_adjustment',
            new_name='is_benefit_adjustment',
        ),
        migrations.AddField(
            model_name='salarycomponents',
            name='is_salary_adjustment',
            field=models.BooleanField(default=False),
        ),
    ]
