# Generated by Django 4.2 on 2023-07-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0002_rename_is_adjustment_salarycomponents_is_benefit_adjustment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarycomponents',
            name='updated_value',
        ),
        migrations.AddField(
            model_name='salarycomponents',
            name='value',
            field=models.IntegerField(db_column='value', default=1),
            preserve_default=False,
        ),
    ]
