# Generated by Django 4.2 on 2023-07-18 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0012_benefits_benefit_category_id'),
        ('salaries', '0003_remove_salarycomponents_updated_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarycomponents',
            name='benefit_scheme_id',
            field=models.ForeignKey(blank=True, db_column='benefit_scheme_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='benefits.benefitscheme'),
        ),
    ]
