# Generated by Django 4.2 on 2023-07-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0004_salarycomponents_benefit_scheme_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryadjustments',
            name='updated_value',
            field=models.IntegerField(db_column='updated_value', default=1),
            preserve_default=False,
        ),
    ]
