# Generated by Django 4.2 on 2023-07-19 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0005_salaryadjustments_updated_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarycomponents',
            name='period_id',
        ),
    ]
