# Generated by Django 4.2 on 2023-07-20 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0006_remove_salarycomponents_period_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalaryAdjustments',
        ),
    ]
