# Generated by Django 4.2 on 2023-07-20 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salaries', '0007_delete_salaryadjustments'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryAdjustments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='', max_length=400, null=True)),
                ('value', models.IntegerField(db_column='value')),
                ('is_deduction', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='created_by_salary_adjustments', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_by_salary_adjustments', to=settings.AUTH_USER_MODEL)),
                ('salary_id', models.ForeignKey(db_column='salary_id', on_delete=django.db.models.deletion.CASCADE, to='salaries.salaries')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_salary_adjustments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Salary Adjustments',
                'db_table': 'salary_adjustments',
                'permissions': (('create_salary_adjustments', 'Create Salary Adjustments'), ('read_salary_adjustments', 'Read Salary Adjustments'), ('update_salary_adjustments', 'Update Salary Adjustments'), ('delete_salary_adjustments', 'Delete Salary Adjustments')),
                'default_permissions': (),
            },
        ),
    ]
