# Generated by Django 4.2 on 2023-07-20 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0008_salaryadjustments'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarycomponents',
            name='salary_adjustments_id',
            field=models.ForeignKey(blank=True, db_column='salary_adjustments_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='salaries.salaryadjustments'),
        ),
    ]
