# Generated by Django 4.2 on 2023-07-20 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0012_benefits_benefit_category_id'),
        ('salaries', '0009_salarycomponents_salary_adjustments_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarycomponents',
            name='benefit_adjustments_id',
            field=models.ForeignKey(blank=True, db_column='benefit_adjustments_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='benefits.benefitadjustments'),
        ),
        migrations.AddField(
            model_name='salarycomponents',
            name='benefit_id',
            field=models.ForeignKey(blank=True, db_column='benefit_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='benefits.benefits'),
        ),
    ]
