# Generated by Django 4.2 on 2023-07-20 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0012_benefits_benefit_category_id'),
        ('salaries', '0010_salarycomponents_benefit_adjustments_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarycomponents',
            name='benefit_id',
            field=models.ForeignKey(blank=True, db_column='benefit_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='benefits.detailemployeebenefits'),
        ),
    ]
