# Generated by Django 4.2 on 2023-07-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0011_alter_salarycomponents_benefit_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaries',
            name='thr',
            field=models.IntegerField(db_column='thr', default=0),
            preserve_default=False,
        ),
    ]
