# Generated by Django 4.2 on 2023-07-24 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overtimes', '0001_initial'),
        ('presences', '0001_initial'),
        ('salaries', '0012_salaries_thr'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarycomponents',
            name='is_overtime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salarycomponents',
            name='is_presence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salarycomponents',
            name='overtime_id',
            field=models.ForeignKey(blank=True, db_column='overtime_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='overtimes.overtimeusers'),
        ),
        migrations.AddField(
            model_name='salarycomponents',
            name='presence_id',
            field=models.ForeignKey(blank=True, db_column='presence_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='presences.presences'),
        ),
    ]
