# Generated by Django 4.2 on 2023-07-24 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0013_salarycomponents_is_overtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarycomponents',
            name='is_presence',
        ),
        migrations.RemoveField(
            model_name='salarycomponents',
            name='presence_id',
        ),
    ]
