# Generated by Django 4.2 on 2023-09-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0015_alter_salaries_leave_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='leave_count',
            field=models.IntegerField(db_column='leave_count', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salaries',
            name='overtime_hours_count',
            field=models.IntegerField(db_column='overtime_hours_count', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salaries',
            name='permit_count',
            field=models.IntegerField(db_column='permit_count', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salaries',
            name='presence_count',
            field=models.IntegerField(blank=True, db_column='presence_count', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salaries',
            name='sick_count',
            field=models.IntegerField(db_column='sick_count', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salaries',
            name='total_work_hours',
            field=models.IntegerField(db_column='total_work_hours', default=0, null=True),
        ),
    ]
