# Generated by Django 4.2 on 2023-12-28 05:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('overtime_rate', models.IntegerField(blank=True, default=0, null=True)),
                ('lembur_rate', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name_plural': 'Settings',
                'db_table': 'settings',
                'permissions': (('create_settings', 'Create Settings'), ('read_settings', 'Read Settings'), ('update_settings', 'Update Settings')),
                'default_permissions': (),
            },
        ),
    ]
