version: '3.8'
services:
  web:
    container_name: web
    image: apotekjaya
    build: 
      context: apotek-jaya/
      dockerfile: Dockerfile.prod
    command: gunicorn apotekjaya.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./apotek-jaya/.env.prod
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./apotek-jaya/.env.prod.db
    ports:
      - '5432:5432'
  
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: