# Generated by Django 4.2 on 2023-05-09 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('benefits', '0003_alter_benefits_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.TextField(blank=True, default='', max_length=400, null=True)),
                ('updated_value', models.IntegerField(default='')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.IntegerField(default=1)),
                ('benefit_id', models.ForeignKey(db_column='benefit_id', on_delete=django.db.models.deletion.CASCADE, to='benefits.benefits')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='created_by_benefit_scheme', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_by_benefit_scheme', to=settings.AUTH_USER_MODEL)),
                ('department_id', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, to='departments.departments')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_benefit_scheme', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Benefit Schemes',
                'db_table': 'benefit_scheme',
                'permissions': (('create_benefit_scheme', 'Create Benefits Scheme'), ('read_benefit_scheme', 'Read Benefits Scheme'), ('update_benefit_scheme', 'Update Benefits Scheme'), ('delete_benefit_scheme', 'Delete Benefits Scheme')),
                'default_permissions': (),
            },
        ),
    ]
