# Generated by Django 4.2 on 2023-05-12 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_alter_employees_expired_at'),
        ('benefits', '0006_detailemployeebenefits_delete_benefitadjustments'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detailemployeebenefits',
            unique_together={('benefit_id', 'benefit_scheme_id', 'employee_id')},
        ),
    ]
