# Generated by Django 4.2 on 2023-06-27 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_alter_employees_expired_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('benefits', '0007_alter_detailemployeebenefits_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitAdjustments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('updated_value', models.IntegerField(default='')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.IntegerField(default=1)),
                ('benefit_id', models.ForeignKey(db_column='benefit_id', on_delete=django.db.models.deletion.CASCADE, to='benefits.benefits')),
                ('benefit_scheme_id', models.ForeignKey(db_column='benefit_scheme_id', on_delete=django.db.models.deletion.CASCADE, to='benefits.benefitscheme')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='created_by_benefit_adjustments', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_by_benefit_adjustments', to=settings.AUTH_USER_MODEL)),
                ('employee_id', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='employees.employees')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_benefit_adjustments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Benefit Adjustments',
                'db_table': 'benefit_adjustments',
                'permissions': (('create_benefit_adjustments', 'Create Benefit Adjustments'), ('read_benefit_adjustments', 'Read Benefit Adjustments'), ('update_benefit_adjustments', 'Update Benefit Adjustments'), ('delete_benefit_adjustments', 'Delete Benefit Adjustments')),
                'default_permissions': (),
                'unique_together': {('benefit_id', 'benefit_scheme_id', 'employee_id')},
            },
        ),
    ]
