# Generated by Django 4.2 on 2023-06-27 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0008_benefitadjustments'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='benefitadjustments',
            unique_together=set(),
        ),
    ]
