# Generated by Django 4.2 on 2023-06-30 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_alter_employees_expired_at'),
        ('benefits', '0009_alter_benefitadjustments_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='benefitadjustments',
            unique_together={('benefit_id', 'benefit_scheme_id', 'employee_id')},
        ),
    ]
