# Generated by Django 4.2 on 2023-07-05 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0011_benefitcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefits',
            name='benefit_category_id',
            field=models.ForeignKey(db_column='benefit_category_id', default=4, on_delete=django.db.models.deletion.CASCADE, to='benefits.benefitcategories'),
            preserve_default=False,
        ),
    ]
