# Generated by Django 4.2 on 2023-08-24 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('benefits', '0012_benefits_benefit_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PTKPType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(default='', max_length=5)),
                ('value', models.IntegerField(default='')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='created_by_ptkp_type', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_by_ptkp_type', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_ptkp_type', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'PTKP Types',
                'db_table': 'ptkp_type',
                'permissions': (('create_ptkp_type', 'Create PTKP Type'), ('read_ptkp_type', 'Read PTKP Type'), ('update_ptkp_type', 'Update PTKP Type'), ('delete_ptkp_type', 'Delete PTKP Type')),
                'default_permissions': (),
            },
        ),
    ]
