# Generated by Django 4.2 on 2023-12-25 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0013_ptkptype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ptkptype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ptkptype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ptkptype',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='ptkptype',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='ptkptype',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ptkptype',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='ptkptype',
            name='updated_by',
        ),
    ]
