# Generated by Django 4.2 on 2023-04-16 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'default_permissions': (), 'permissions': (('create_employees', 'Create Employees'), ('read_employees', 'Read Employees'), ('update_employees', 'Update Employees'), ('delete_employees', 'Delete Employees')), 'verbose_name_plural': 'Employees'},
        ),
    ]
