# Generated by Django 4.2 on 2023-04-17 01:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'default_permissions': (), 'permissions': (('create_employees', 'Create Employees'), ('read_employees', 'Read Employees'), ('update_employees', 'Update Employees'), ('delete_employees', 'Delete Employees')), 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterField(
            model_name='employees',
            name='expired_at',
            field=models.DateField(default=datetime.date(2024, 4, 16)),
        ),
    ]
