# Generated by Django 4.2 on 2023-04-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='expired_at',
            field=models.DateField(default='2023-10-10'),
            preserve_default=False,
        ),
    ]
