# Generated by Django 4.2 on 2023-04-07 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0002_remove_employees_email_employees_auth_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='auth_user_id',
            field=models.OneToOneField(db_column='auth_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_id_employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employees',
            name='created_by',
            field=models.OneToOneField(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='created_by_employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employees',
            name='deleted_by',
            field=models.OneToOneField(db_column='deleted_by', on_delete=django.db.models.deletion.CASCADE, related_name='deleted_by_employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employees',
            name='updated_by',
            field=models.OneToOneField(db_column='updated_by', on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_employees', to=settings.AUTH_USER_MODEL),
        ),
    ]
