# Generated by Django 4.2 on 2023-04-13 06:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0002_alter_employees_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='created_by_employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employees',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_by_employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employees',
            name='expired_at',
            field=models.DateField(default=datetime.date(2024, 4, 12)),
        ),
        migrations.AlterField(
            model_name='employees',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_employees', to=settings.AUTH_USER_MODEL),
        ),
    ]
