# Generated by Django 4.2 on 2023-04-07 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0003_alter_employees_auth_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='address',
            field=models.CharField(default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='birthplace',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='bloodtype',
            field=models.CharField(default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='deleted_by',
            field=models.OneToOneField(db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_by_employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employees',
            name='domicile',
            field=models.CharField(default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='education',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='join_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='nik',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='npwp',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='phone',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='employees',
            name='updated_by',
            field=models.OneToOneField(db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_employees', to=settings.AUTH_USER_MODEL),
        ),
    ]
