# Generated by Django 4.2 on 2023-04-13 09:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employees_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='hash_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
