# Generated by Django 4.2 on 2023-04-14 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employees_hash_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='expired_at',
            field=models.DateField(default=datetime.date(2024, 4, 13)),
        ),
    ]
