# Generated by Django 4.2 on 2023-05-01 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authusergroupextended',
            name='aug_department_id',
            field=models.ForeignKey(db_column='department_id', default=5, on_delete=django.db.models.deletion.CASCADE, related_name='aug_department_id', to='departments.departments'),
            preserve_default=False,
        ),
    ]
