# Generated by Django 4.2 on 2023-05-01 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employees_expired_at'),
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permission', '0002_authusergroupextended_aug_department_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='authusergroupextended',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='authusergroupextended',
            name='aug_employee_id',
            field=models.ForeignKey(db_column='employee_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='aug_employee_id', to='employees.employees'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='authusergroupextended',
            unique_together={('aug_user_id', 'aug_employee_id', 'aug_department_id')},
        ),
        migrations.RemoveField(
            model_name='authusergroupextended',
            name='aug_group_id',
        ),
    ]
