# Generated by Django 4.2 on 2023-05-01 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employees_expired_at'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('departments', '0001_initial'),
        ('permission', '0003_alter_authusergroupextended_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='authusergroupextended',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='authusergroupextended',
            name='aug_group_id',
            field=models.ForeignKey(db_column='group_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='aug_group_id', to='auth.group'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='authusergroupextended',
            unique_together={('aug_employee_id', 'aug_group_id', 'aug_department_id')},
        ),
        migrations.RemoveField(
            model_name='authusergroupextended',
            name='aug_user_id',
        ),
    ]
