# Generated by Django 4.2 on 2023-05-06 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0004_alter_authusergroupextended_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='authusergroupextended',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='authusergroupextended',
            name='aug_department_id',
        ),
        migrations.RemoveField(
            model_name='authusergroupextended',
            name='aug_employee_id',
        ),
        migrations.RemoveField(
            model_name='authusergroupextended',
            name='aug_group_id',
        ),
        migrations.RemoveField(
            model_name='authusergroupextended',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='authusergroupextended',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='authusergroupextended',
            name='updated_by',
        ),
        migrations.AlterUniqueTogether(
            name='authuserpermissionextended',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='authuserpermissionextended',
            name='aup_permission_id',
        ),
        migrations.RemoveField(
            model_name='authuserpermissionextended',
            name='aup_user_id',
        ),
        migrations.RemoveField(
            model_name='authuserpermissionextended',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='authuserpermissionextended',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='authuserpermissionextended',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='authgroupextended',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='authgroupextended',
            name='deleted_by',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissionExtended',
        ),
        migrations.DeleteModel(
            name='AuthUserGroupExtended',
        ),
        migrations.DeleteModel(
            name='AuthUserPermissionExtended',
        ),
    ]
