# Generated by Django 4.2 on 2023-07-23 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salaries', '0011_alter_salarycomponents_benefit_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.TextField(blank=True, default='', max_length=400, null=True)),
                ('max_duration', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='created_by_leaves', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_by_leaves', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_leaves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Leaves',
                'db_table': 'leaves',
                'permissions': (('create_leaves', 'Create Leave'), ('read_leaves', 'Read Leave'), ('update_leaves', 'Update Leave'), ('delete_leaves', 'Delete Leave')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='LeaveRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('reason', models.TextField(blank=True, default='', max_length=400, null=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('duration', models.IntegerField(default=1)),
                ('approved_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('rejected_reason', models.TextField(blank=True, default='', max_length=400, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.IntegerField(default=1)),
                ('approved_by', models.ForeignKey(blank=True, db_column='approved_by', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by_leave_requests', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='created_by_leave_requests', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_by_leave_requests', to=settings.AUTH_USER_MODEL)),
                ('employee_id', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('leave_type_id', models.ForeignKey(db_column='leave_type_id', on_delete=django.db.models.deletion.CASCADE, to='leaves.leaves')),
                ('period_id', models.ForeignKey(db_column='period_id', on_delete=django.db.models.deletion.CASCADE, to='salaries.payrollperiods')),
                ('rejected_by', models.ForeignKey(blank=True, db_column='rejected_by', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rejected_by_leave_requests', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Leave Requests',
                'db_table': 'leave_requests',
                'permissions': (('create_leave_requests', 'Create Leave Requests'), ('read_leave_requests', 'Read Leave Requests'), ('update_leave_requests', 'Update Leave Requests'), ('delete_leave_requests', 'Delete Leave Requests')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='LeaveBalances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('balance', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='created_by_leave_balances', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_by_leave_balances', to=settings.AUTH_USER_MODEL)),
                ('employee_id', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('leave_type_id', models.ForeignKey(db_column='leave_type_id', on_delete=django.db.models.deletion.CASCADE, to='leaves.leaves')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_leave_balances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Leave Balances',
                'db_table': 'leave_balances',
                'permissions': (('create_leave_balances', 'Create Leave Balances'), ('read_leave_balances', 'Read Leave Balances'), ('update_leave_balances', 'Update Leave Balances'), ('delete_leave_balances', 'Delete Leave Balances')),
                'default_permissions': (),
            },
        ),
    ]
