# Generated by Django 4.2 on 2023-07-25 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalances',
            name='leave_type_id',
            field=models.ForeignKey(db_column='leave_id', on_delete=django.db.models.deletion.CASCADE, to='leaves.leaves'),
        ),
    ]
