# Generated by Django 4.2 on 2023-07-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_alter_leavebalances_leave_type_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavebalances',
            old_name='leave_type_id',
            new_name='leave_id',
        ),
        migrations.AlterField(
            model_name='leavebalances',
            name='balance',
            field=models.IntegerField(default=1),
        ),
    ]
