# Generated by Django 4.2 on 2023-07-26 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0024_alter_employees_expired_at'),
        ('leaves', '0004_leavebalances_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalances',
            name='employee_id',
            field=models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='employees.employees'),
        ),
    ]
