# Generated by Django 4.2 on 2023-05-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0002_alter_benefits_options_alter_benefits_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefits',
            name='description',
            field=models.TextField(blank=True, default='', max_length=400, null=True),
        ),
    ]
