# Generated by Django 4.2 on 2023-05-12 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0010_alter_employees_expired_at'),
        ('benefits', '0005_remove_benefitscheme_benefit_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailEmployeeBenefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.IntegerField(default=1)),
                ('benefit_id', models.ForeignKey(db_column='benefit_id', on_delete=django.db.models.deletion.CASCADE, to='benefits.benefits')),
                ('benefit_scheme_id', models.ForeignKey(db_column='benefit_scheme_id', on_delete=django.db.models.deletion.CASCADE, to='benefits.benefitscheme')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='created_by_detail_employee_benefits', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_by_detail_employee_benefits', to=settings.AUTH_USER_MODEL)),
                ('employee_id', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='employees.employees')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_detail_employee_benefits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Detail Employee Benefits',
                'db_table': 'detail_employee_benefits',
                'permissions': (('create_detail_employee_benefits', 'Create Detail Employee Benefits'), ('read_detail_employee_benefits', 'Read Detail Employee Benefits'), ('update_detail_employee_benefits', 'Update Detail Employee Benefits'), ('delete_detail_employee_benefits', 'Delete Detail Employee Benefits')),
                'default_permissions': (),
            },
        ),
        migrations.DeleteModel(
            name='BenefitAdjustments',
        ),
    ]
