# Generated by Django 4.2 on 2023-07-15 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0017_alter_employees_expired_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overtimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.TextField(blank=True, default='', max_length=400, null=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='created_by_overtimes', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_by_overtimes', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_overtimes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Overtimes',
                'db_table': 'overtimes',
                'permissions': (('create_overtimes', 'Create Overtimes'), ('read_overtimes', 'Read Overtimes'), ('update_overtimes', 'Update Overtimes'), ('delete_overtimes', 'Delete Overtimes')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='OvertimeUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='created_by_overtime_users', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_by_overtime_users', to=settings.AUTH_USER_MODEL)),
                ('employee_id', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='employees.employees')),
                ('overtime_id', models.ForeignKey(db_column='overtime_id', on_delete=django.db.models.deletion.CASCADE, to='overtimes.overtimes')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_overtime_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Overtime Users',
                'db_table': 'overtime_users',
                'permissions': (('create_overtime_users', 'Create Overtime Users'), ('read_overtime_users', 'Read Overtime Users'), ('update_overtime_users', 'Update Overtime Users'), ('delete_overtime_users', 'Delete Overtime Users')),
                'default_permissions': (),
            },
        ),
    ]
