# Generated by Django 4.2 on 2023-12-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtimes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimes',
            name='is_overtime',
            field=models.BooleanField(default=True),
        ),
    ]
