# Generated by Django 4.2 on 2023-12-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtimes', '0002_overtimes_is_overtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overtimes',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='overtimes',
            name='deleted_by',
        ),
        migrations.AddField(
            model_name='overtimes',
            name='date',
            field=models.DateField(default='1970-01-01'),
            preserve_default=False,
        ),
    ]
