# Generated by Django 4.2 on 2023-12-26 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('overtimes', '0003_remove_overtimes_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtimes',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_overtimes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='overtimes',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by_overtimes', to=settings.AUTH_USER_MODEL),
        ),
    ]
