# Generated by Django 4.2 on 2023-12-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtimes', '0004_alter_overtimes_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overtimeusers',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='overtimeusers',
            name='deleted_by',
        ),
        migrations.AlterField(
            model_name='overtimes',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
