# Generated by Django 4.2 on 2023-12-27 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overtimes', '0005_remove_overtimeusers_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='overtimes',
            unique_together={('name', 'date', 'start_at', 'end_at')},
        ),
    ]
