# Generated by Django 4.2 on 2023-12-27 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overtimes', '0006_alter_overtimes_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='overtimes',
            unique_together={('name', 'date', 'start_at', 'end_at', 'is_overtime')},
        ),
    ]
