# Generated by Django 4.2 on 2023-07-23 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0021_alter_employees_expired_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='created_by_presences', to=settings.AUTH_USER_MODEL)),
                ('employee_id', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='employees.employees')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_presences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Presences',
                'db_table': 'presences',
                'permissions': (('create_presences', 'Create Presence'), ('read_presences', 'Read Presence'), ('update_presences', 'Update Presence'), ('delete_presences', 'Delete Presence')),
                'default_permissions': (),
            },
        ),
    ]
