# Generated by Django 4.2 on 2023-12-26 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presences',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_presences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='presences',
            name='end_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='presences',
            name='start_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='presences',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by_presences', to=settings.AUTH_USER_MODEL),
        ),
    ]
