# Generated by Django 4.2 on 2023-12-26 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0033_alter_employees_nik'),
        ('presences', '0002_alter_presences_created_by_alter_presences_end_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='presences',
            unique_together={('employee_id', 'start_at', 'end_at')},
        ),
    ]
